/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SnapCompareRouteImport } from './routes/snap-compare'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as HomeProfileRouteImport } from './routes/home-profile'
import { Route as DesignRouteImport } from './routes/design'
import { Route as IndexRouteImport } from './routes/index'

const SnapCompareRoute = SnapCompareRouteImport.update({
  id: '/snap-compare',
  path: '/snap-compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeProfileRoute = HomeProfileRouteImport.update({
  id: '/home-profile',
  path: '/home-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/home-profile': typeof HomeProfileRoute
  '/scanner': typeof ScannerRoute
  '/snap-compare': typeof SnapCompareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/home-profile': typeof HomeProfileRoute
  '/scanner': typeof ScannerRoute
  '/snap-compare': typeof SnapCompareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design': typeof DesignRoute
  '/home-profile': typeof HomeProfileRoute
  '/scanner': typeof ScannerRoute
  '/snap-compare': typeof SnapCompareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/design' | '/home-profile' | '/scanner' | '/snap-compare'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/design' | '/home-profile' | '/scanner' | '/snap-compare'
  id:
    | '__root__'
    | '/'
    | '/design'
    | '/home-profile'
    | '/scanner'
    | '/snap-compare'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignRoute: typeof DesignRoute
  HomeProfileRoute: typeof HomeProfileRoute
  ScannerRoute: typeof ScannerRoute
  SnapCompareRoute: typeof SnapCompareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/snap-compare': {
      id: '/snap-compare'
      path: '/snap-compare'
      fullPath: '/snap-compare'
      preLoaderRoute: typeof SnapCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-profile': {
      id: '/home-profile'
      path: '/home-profile'
      fullPath: '/home-profile'
      preLoaderRoute: typeof HomeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignRoute: DesignRoute,
  HomeProfileRoute: HomeProfileRoute,
  ScannerRoute: ScannerRoute,
  SnapCompareRoute: SnapCompareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
