/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValuationRouteImport } from './routes/valuation'
import { Route as SnapCompareRouteImport } from './routes/snap-compare'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as InvestorRouteImport } from './routes/investor'
import { Route as HomeProfileRouteImport } from './routes/home-profile'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FloorPlanRouteImport } from './routes/floor-plan'
import { Route as DesignRouteImport } from './routes/design'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const ValuationRoute = ValuationRouteImport.update({
  id: '/valuation',
  path: '/valuation',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapCompareRoute = SnapCompareRouteImport.update({
  id: '/snap-compare',
  path: '/snap-compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorRoute = InvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeProfileRoute = HomeProfileRouteImport.update({
  id: '/home-profile',
  path: '/home-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorPlanRoute = FloorPlanRouteImport.update({
  id: '/floor-plan',
  path: '/floor-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/companies': typeof CompaniesRoute
  '/design': typeof DesignRoute
  '/floor-plan': typeof FloorPlanRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home-profile': typeof HomeProfileRoute
  '/investor': typeof InvestorRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scanner': typeof ScannerRoute
  '/snap-compare': typeof SnapCompareRoute
  '/valuation': typeof ValuationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/companies': typeof CompaniesRoute
  '/design': typeof DesignRoute
  '/floor-plan': typeof FloorPlanRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home-profile': typeof HomeProfileRoute
  '/investor': typeof InvestorRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scanner': typeof ScannerRoute
  '/snap-compare': typeof SnapCompareRoute
  '/valuation': typeof ValuationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/companies': typeof CompaniesRoute
  '/design': typeof DesignRoute
  '/floor-plan': typeof FloorPlanRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home-profile': typeof HomeProfileRoute
  '/investor': typeof InvestorRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scanner': typeof ScannerRoute
  '/snap-compare': typeof SnapCompareRoute
  '/valuation': typeof ValuationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/companies'
    | '/design'
    | '/floor-plan'
    | '/forgot-password'
    | '/home-profile'
    | '/investor'
    | '/pricing'
    | '/profile'
    | '/projects'
    | '/reset-password'
    | '/scanner'
    | '/snap-compare'
    | '/valuation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/companies'
    | '/design'
    | '/floor-plan'
    | '/forgot-password'
    | '/home-profile'
    | '/investor'
    | '/pricing'
    | '/profile'
    | '/projects'
    | '/reset-password'
    | '/scanner'
    | '/snap-compare'
    | '/valuation'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chat'
    | '/companies'
    | '/design'
    | '/floor-plan'
    | '/forgot-password'
    | '/home-profile'
    | '/investor'
    | '/pricing'
    | '/profile'
    | '/projects'
    | '/reset-password'
    | '/scanner'
    | '/snap-compare'
    | '/valuation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  CompaniesRoute: typeof CompaniesRoute
  DesignRoute: typeof DesignRoute
  FloorPlanRoute: typeof FloorPlanRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeProfileRoute: typeof HomeProfileRoute
  InvestorRoute: typeof InvestorRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScannerRoute: typeof ScannerRoute
  SnapCompareRoute: typeof SnapCompareRoute
  ValuationRoute: typeof ValuationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/valuation': {
      id: '/valuation'
      path: '/valuation'
      fullPath: '/valuation'
      preLoaderRoute: typeof ValuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snap-compare': {
      id: '/snap-compare'
      path: '/snap-compare'
      fullPath: '/snap-compare'
      preLoaderRoute: typeof SnapCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor': {
      id: '/investor'
      path: '/investor'
      fullPath: '/investor'
      preLoaderRoute: typeof InvestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-profile': {
      id: '/home-profile'
      path: '/home-profile'
      fullPath: '/home-profile'
      preLoaderRoute: typeof HomeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floor-plan': {
      id: '/floor-plan'
      path: '/floor-plan'
      fullPath: '/floor-plan'
      preLoaderRoute: typeof FloorPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  CompaniesRoute: CompaniesRoute,
  DesignRoute: DesignRoute,
  FloorPlanRoute: FloorPlanRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeProfileRoute: HomeProfileRoute,
  InvestorRoute: InvestorRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScannerRoute: ScannerRoute,
  SnapCompareRoute: SnapCompareRoute,
  ValuationRoute: ValuationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
